% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Dec-2021 15:45:00
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

HH = saveVarsMat.HH; % <128x128 double> too many elements

HHN = saveVarsMat.HHN; % <128x128 logical> too many elements

HHNY = saveVarsMat.HHNY; % <129x129 logical> too many elements

HHY = saveVarsMat.HHY; % <129x129 double> too many elements

HL = saveVarsMat.HL; % <128x128 double> too many elements

HLN = saveVarsMat.HLN; % <128x128 logical> too many elements

HLNY = saveVarsMat.HLNY; % <129x129 logical> too many elements

HLY = saveVarsMat.HLY; % <129x129 double> too many elements

LH = saveVarsMat.LH; % <128x128 double> too many elements

LHN = saveVarsMat.LHN; % <128x128 logical> too many elements

LHNY = saveVarsMat.LHNY; % <129x129 logical> too many elements

LHY = saveVarsMat.LHY; % <129x129 double> too many elements

LL = saveVarsMat.LL; % <128x128 double> too many elements

LLY = saveVarsMat.LLY; % <129x129 double> too many elements

Result = saveVarsMat.Result; % <256x256 double> too many elements

Result1 = saveVarsMat.Result1; % <256x256 double> too many elements

X = saveVarsMat.X; % <256x256 uint8> too many elements

XFUSmean = saveVarsMat.XFUSmean; % <256x256 double> too many elements

XX = [256 256];

Y = saveVarsMat.Y; % <256x256 uint8> too many elements

YY = [256 256];

imagename1 = 's06_CT.tif';

imagename2 = 's06_MRT2.tif';

imagepath1 = 'C:\Users\Manoj Kumar\Desktop\MY PROJECT\CT-MRT2\';

imagepath2 = 'C:\Users\Manoj Kumar\Desktop\MY PROJECT\CT-MRT2\';

j = [];

m = saveVarsMat.m; % <0x1 double> empty object

n = saveVarsMat.n; % <0x1 double> empty object

o = saveVarsMat.o; % <0x1 double> empty object

p = saveVarsMat.p; % <0x1 double> empty object

tmp = saveVarsMat.tmp; % <128x128 double> too many elements

tmp1 = saveVarsMat.tmp1; % <128x128 double> too many elements

tmp2 = saveVarsMat.tmp2; % <128x128 double> too many elements

tmp3 = saveVarsMat.tmp3; % <129x129 double> too many elements

clear saveVarsMat;
